-- Self-learning pipeline: content gaps, confidence feedback loop, question clusters.
-- Supports automatic knowledge improvement from chat interactions.

---------------------------------------------------------------------------
-- 1. feedback_boost on winery_chunks — tracks net thumbs up/down per chunk
---------------------------------------------------------------------------
alter table public.winery_chunks
  add column if not exists feedback_boost int not null default 0;

comment on column public.winery_chunks.feedback_boost is
  'Net feedback score: +1 per thumbs-up on responses using this chunk, -1 per thumbs-down. Used to adjust effective confidence at retrieval time.';

---------------------------------------------------------------------------
-- 2. content_gaps — auto-detected knowledge holes from deflections
---------------------------------------------------------------------------
create table if not exists public.content_gaps (
  id uuid primary key default gen_random_uuid(),
  winery_id uuid references public.wineries(id) on delete cascade,
  gap_summary text not null,
  sample_questions text[] not null default '{}',
  frequency int not null default 1,
  status text not null default 'open'
    check (status in ('open', 'auto_filled', 'dismissed', 'resolved')),
  auto_chunk_id uuid references public.winery_chunks(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_content_gaps_winery_status
  on public.content_gaps(winery_id, status);

comment on table public.content_gaps is
  'Knowledge gaps detected from deflected chat responses. Nightly pipeline populates; admin or auto-fill resolves.';

---------------------------------------------------------------------------
-- 3. question_clusters — frequent question patterns per winery per month
---------------------------------------------------------------------------
create table if not exists public.question_clusters (
  id uuid primary key default gen_random_uuid(),
  winery_id uuid references public.wineries(id) on delete cascade,
  cluster_label text not null,
  sample_questions text[] not null default '{}',
  question_count int not null default 0,
  avg_retrieval_score float,
  avg_feedback float,
  period_start date not null,
  period_end date not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_question_clusters_winery_period
  on public.question_clusters(winery_id, period_start);

comment on table public.question_clusters is
  'Monthly clusters of similar visitor questions per winery. Generated by the learning pipeline to surface what visitors ask most and where retrieval quality is weak.';

---------------------------------------------------------------------------
-- 4. Update match_chunks to factor in feedback_boost
--    Effective confidence = confidence + (feedback_boost * 0.02), clamped [0.5, 1.0]
--    Chunks with many downvotes naturally drop below the 0.7 gate
---------------------------------------------------------------------------
create or replace function public.match_chunks(
  query_embedding vector(1536),
  winery_id_filter uuid,
  match_count int default 5
)
returns table (
  id uuid,
  chunk_text text,
  chunk_type text,
  source_url text,
  fetched_at timestamptz,
  similarity float
)
language sql
stable
as $$
  with ref as (
    select w.id from public.wineries w where w.slug = 'pairing-reference' limit 1
  )
  select
    wc.id,
    wc.chunk_text,
    wc.chunk_type,
    wc.source_url,
    wc.fetched_at,
    (1 - (wc.embedding <=> query_embedding))::float as similarity
  from public.winery_chunks wc, ref
  where least(1.0, greatest(0.5, wc.confidence + wc.feedback_boost * 0.02)) >= 0.7
    and wc.embedding is not null
    and (wc.winery_id = winery_id_filter or wc.winery_id = ref.id)
  order by wc.embedding <=> query_embedding
  limit greatest(1, least(match_count, 20));
$$;

---------------------------------------------------------------------------
-- 5. RPC: adjust_chunk_feedback — called after thumbs up/down
---------------------------------------------------------------------------
create or replace function public.adjust_chunk_feedback(
  p_chunk_ids uuid[],
  p_delta int  -- +1 for thumbs up, -1 for thumbs down
)
returns void
language sql
as $$
  update public.winery_chunks
  set feedback_boost = feedback_boost + p_delta
  where id = any(p_chunk_ids);
$$;

---------------------------------------------------------------------------
-- 6. RPC: get_deflected_questions — used by learning pipeline
---------------------------------------------------------------------------
create or replace function public.get_deflected_questions(
  p_winery_id uuid,
  p_since timestamptz default (now() - interval '24 hours')
)
returns table (
  user_message text,
  retrieved_chunk_ids uuid[],
  retrieval_scores float[],
  created_at timestamptz
)
language sql
stable
as $$
  select cl.user_message, cl.retrieved_chunk_ids, cl.retrieval_scores, cl.created_at
  from public.chat_logs cl
  where cl.winery_id = p_winery_id
    and cl.was_deflected = true
    and cl.created_at >= p_since
  order by cl.created_at desc;
$$;

---------------------------------------------------------------------------
-- 7. RPC: get_question_stats — aggregated question data for clustering
---------------------------------------------------------------------------
create or replace function public.get_question_stats(
  p_winery_id uuid,
  p_since timestamptz,
  p_until timestamptz default now()
)
returns table (
  user_message text,
  retrieval_scores float[],
  feedback_rating smallint,
  created_at timestamptz
)
language sql
stable
as $$
  select cl.user_message, cl.retrieval_scores, cl.feedback_rating, cl.created_at
  from public.chat_logs cl
  where cl.winery_id = p_winery_id
    and cl.created_at >= p_since
    and cl.created_at < p_until
  order by cl.created_at desc
  limit 2000;
$$;
